name: Rust Static Builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-hello-cargo:
    runs-on: ubuntu-latest
    container:
      image: clux/muslrust:stable
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install Rust with musl target
      run: |
        rustup target add x86_64-unknown-linux-musl

    - name: Build hello_cargo
      run: |
        cd hello_cargo
        cargo build --release --target x86_64-unknown-linux-musl

    - name: Upload hello_cargo binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello_cargo
        path: hello_cargo/target/x86_64-unknown-linux-musl/release/hello_cargo

